# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-18 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import libros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('anhoPublicacion', models.IntegerField(null=True)),
                ('edicion', models.IntegerField(null=True)),
                ('imagenPortada', models.ImageField(null=True, upload_to=libros.models.uploadPortada)),
                ('cantidadEjemplares', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
